# -*- coding: utf-8 -*-
"""internship markov_chain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHsH41CBUEqDOjhphUE8Z9ZHZRO4AsvE
"""

!pip install markovify

text = """
Artificial intelligence is transforming the world.
Machine learning helps computers learn patterns.
Deep learning is a subset of machine learning.
AI is useful in healthcare and education.
Technology is evolving rapidly every year.
Computers can analyze large amounts of data quickly.
Data science combines statistics and programming.
Neural networks are inspired by the human brain.
Automation is changing industries around the globe.
Python is one of the most popular programming languages.
Artificial intelligence can improve healthcare systems.
Students are learning AI and machine learning skills.
Technology helps people communicate faster.
Software development is an important technical skill.
Digital transformation is growing worldwide.
"""

with open("data.txt", "w") as file:
    file.write(text)

print("data.txt updated successfully")

import markovify

# Read file
with open("data.txt", "r", encoding="utf-8") as file:
    text = file.read()

# Create model
model = markovify.Text(text, state_size=1)

print("Generated Text:\n")

# Generate 5 sentences
for i in range(5):

    sentence = model.make_sentence(tries=100)

    if sentence:
        print(sentence)

